# steps:
#   #Build the container image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'us-central1-docker.pkg.dev/dbms-lab-414417/microservice2/service2:latest', '.']

#   #Push the container image to Artifact Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-central1-docker.pkg.dev/dbms-lab-414417/microservice2/service2:latest']

#   #copying from google cloud storage
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args:
#       - 'cp'
#       - 'gs://deployment-kubectl/deployment.yaml'
#       - '/workspace/deployment.yaml'

#   #FOR GKE
#   - name: 'gcr.io/cloud-builders/kubectl'
#     args:
#       - 'apply'
#       - '-f'
#       - '/workspace/deployment.yaml'

#     env:
#       - 'CLOUDSDK_COMPUTE_REGION=us-central1-c'
#       - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
#       - 'CLOUDSDK_CONTAINER_CLUSTER=k8cluster'

# options: 
#   logging: CLOUD_LOGGING_ONLY

steps:
  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/dbms-lab-414417/microservice2/service2:latest', '.' ]

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/dbms-lab-414417/microservice2/service2:latest'
    ]

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'apply',
      '-f',
      'deployment2.yaml'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=k8cluster'
      - 'CLOUDSDK_CORE_PROJECT=dbms-lab-414417'

images:
  - 'us-central1-docker.pkg.dev/dbms-lab-414417/microservice2/service2:latest'

logsBucket: "gs://cloudrunlogsjk"
serviceAccount: "955032749416-compute@developer.gserviceaccount.com"